server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:nacos:
  cloud:
    nacos:
      config:
        enabled: false
        import-check:
          enabled: false
      discovery:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: system-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=1

        - id: enterprise-service
          uri: lb://enterprise-service
          predicates:
            - Path=/api/enterprise/**
          filters:
            - StripPrefix=2

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2

        - id: license-service
          uri: lb://license-service
          predicates:
            - Path=/api/license/**
          filters:
            - StripPrefix=2

        - id: supervision-service
          uri: lb://supervision-service
          predicates:
            - Path=/api/supervision/**
          filters:
            - StripPrefix=2

        - id: risk-service
          uri: lb://risk-service
          predicates:
            - Path=/api/risk/**
          filters:
            - StripPrefix=2

    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0 